//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MID_PROJECT.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_profile()
        {
            this.blogs = new HashSet<blog>();
        }
    
        public int id { get; set; }
        public int a_id { get; set; }
        public string a_name { get; set; }
        public string a_address { get; set; }
        public string a_img { get; set; }
        public string a_email { get; set; }
        public string a_num { get; set; }
    
        public virtual user_details user_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blog> blogs { get; set; }
    }
}
