//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MID_PROJECT.Models.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class b_profile
    {
        public int id { get; set; }
        public int b_id { get; set; }
        public string b_name { get; set; }
        public string b_address { get; set; }
        public string b_img { get; set; }
        public string b_email { get; set; }
        public string b_num { get; set; }
    
        public virtual user_details user_details { get; set; }
    }
}
