//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MID_PROJECT.Models.database
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class blog
    {
        public int id { get; set; }
        public Nullable<int> a_id { get; set; }
        public string img { get; set; }

        public HttpPostedFileBase File { get; set; }
        public string title { get; set; }
        public string date { get; set; }
        public string details { get; set; }
    
        public virtual a_profile a_profile { get; set; }
    }
}
