//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MID_PROJECT.Models.database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIDEntities10 : DbContext
    {
        public MIDEntities10()
            : base("name=MIDEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_profile> a_profile { get; set; }
        public virtual DbSet<b_profile> b_profile { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<c_rating> c_rating { get; set; }
        public virtual DbSet<s_appartment_details> s_appartment_details { get; set; }
        public virtual DbSet<s_profile> s_profile { get; set; }
        public virtual DbSet<t_profile> t_profile { get; set; }
        public virtual DbSet<trans_details_sb> trans_details_sb { get; set; }
        public virtual DbSet<user_details> user_details { get; set; }
    }
}
